# Generated by Django 4.1 on 2022-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0003_alter_attendance_options_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
