# Generated by Django 4.1 on 2022-09-15 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0005_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 21, 51, 24, 273844), null=True),
        ),
    ]
