# Generated by Django 4.1 on 2022-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0008_remove_attendance_absent_attendance_class_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
