# Generated by Django 4.1 on 2022-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0009_alter_attendance_class_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
