# Generated by Django 4.1 on 2022-09-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0010_alter_attendance_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
