# Generated by Django 4.1 on 2022-09-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0011_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
