# Generated by Django 4.1 on 2022-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0014_remove_attendance_updated_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_no',
            field=models.IntegerField(default=0),
        ),
    ]
