# Generated by Django 4.0 on 2022-07-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
