# Generated by Django 4.0 on 2022-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_1',
            new_name='present_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='new_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='old_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
