# Generated by Django 4.0 on 2022-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0007_rename_address_1_profile_present_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='select_dept',
            field=models.IntegerField(blank=True, choices=[(1, 'Science'), (2, 'Arts'), (3, 'Commerce'), (4, 'Under class 9')], null=True),
        ),
    ]
