# Generated by Django 4.0 on 2022-08-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_remove_profile_blood_group_remove_profile_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='select_dept',
            new_name='select_department',
        ),
    ]
