# Generated by Django 4.0 on 2022-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_rename_select_dept_profile_select_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_class',
            field=models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_department',
            field=models.CharField(blank=True, choices=[('1', 'Science'), ('2', 'Arts'), ('3', 'Commerce'), ('4', 'Under class 9')], max_length=20, null=True),
        ),
    ]
