# Generated by Django 4.0 on 2022-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0011_alter_profile_select_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_department',
            field=models.IntegerField(blank=True, choices=[(1, 'Science'), (2, 'Arts'), (3, 'Commerce'), (4, 'Select this option if you want to admit Under class 9')], null=True),
        ),
    ]
