# Generated by Django 4.0 on 2022-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0012_profile_zipcode_alter_profile_select_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
