# Generated by Django 4.1 on 2022-09-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0013_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
