# Generated by Django 4.0 on 2022-10-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0014_profile_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
