# Generated by Django 4.0 on 2022-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0009_alter_teacher_subject_1_alter_teacher_subject_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_2',
            field=models.IntegerField(choices=[(1, 'Bangla 1st paper'), (2, 'Bangla 2nd paper'), (3, 'English-1st paper'), (3, 'English 2nd paper'), (4, 'Mathematics')], default=4),
        ),
    ]
