# Generated by Django 4.1 on 2022-10-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Login', '0014_profile_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField(default=0)),
                ('test2', models.IntegerField(default=0)),
                ('test3', models.IntegerField(default=0)),
                ('test4', models.IntegerField(default=0)),
                ('test5', models.IntegerField(default=0)),
                ('test6', models.IntegerField(default=0)),
                ('test7', models.IntegerField(default=0)),
                ('test8', models.IntegerField(default=0)),
                ('test9', models.IntegerField(default=0)),
                ('test10', models.IntegerField(default=0)),
                ('performance1', models.IntegerField(default=0)),
                ('performance2', models.IntegerField(default=0)),
                ('performance3', models.IntegerField(default=0)),
                ('performance4', models.IntegerField(default=0)),
                ('performance5', models.IntegerField(default=0)),
                ('performance6', models.IntegerField(default=0)),
                ('performance7', models.IntegerField(default=0)),
                ('performance8', models.IntegerField(default=0)),
                ('performance9', models.IntegerField(default=0)),
                ('performance10', models.IntegerField(default=0)),
                ('midterm', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Login.profile')),
            ],
        ),
    ]
