# Generated by Django 4.1 on 2022-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='session',
            field=models.IntegerField(verbose_name=2022),
        ),
    ]
