# Generated by Django 4.1 on 2022-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0002_alter_mark_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='user',
        ),
    ]
