# Generated by Django 4.1 on 2022-10-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0004_mark_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='user',
            new_name='profile',
        ),
    ]
