# Generated by Django 4.1 on 2022-10-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0005_rename_user_mark_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='profile',
        ),
    ]
