# Generated by Django 4.1 on 2022-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0011_alter_grade_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
