# Generated by Django 4.0 on 2022-10-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0015_alter_grade_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
