# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0016_grade_class_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
