# Generated by Django 4.1 on 2022-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mark', '0017_grade_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
